config/routes.rb
Rails.application.routes.draw do
  get 'login/index'
  post 'login/signin'
  get 'login/signup'
  delete 'login/signout'

  resources :users, only: [:new, :create] do
    resources :posts

    get 'all_posts', to: 'posts#all'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'login#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :body, presence: true
  validates :body, length: { minimum: 1 }
end

app/models/user.rb
require "#{Rails.root}/lib/commons"
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :login, uniqueness: true
  validates :login, :password, presence: true
  validates :password, :login, length: { minimum: 3 }

  attr_accessor :password_plaintext
  before_save :hashfy

  private
  def hashfy
    if password_plaintext.present?
      self.password = Commons::Encripter.new.hashify(password_plaintext)
    else
      throw :abort
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate
    if result = User::Authorize.(params, :user_id => { "id" => session[:current_user_id] })
      return @user = result["user"]
    end

    redirect_to login_index_path, flash: { error:  "You must be logged in to access this section" }
  end
end

app/controllers/login_controller.rb
require "#{Rails.root}/lib/commons"
class LoginController < ApplicationController
  def index
  end

  def signup
  end

  def signin
    run User::Login do |result|
      session[:current_user_id] = result["model"].id
      return redirect_to user_posts_path(result["model"])
    end

    flash.now[:error] = "Wrong credentials"
    render action: 'index'
  end

  def signout
    session.delete(:current_user_id)
    render 'index'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate
  layout "navbar"

  def index
  end

  def create
    Post::Create.(params)
    redirect_to user_posts_path(@user)
  end

  def destroy
    Post::Delete.(params)
    redirect_to user_posts_path(@user)
  end

  def all
    result = Post::All.()
    @posts = result["model"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    run User::Create::Present do |result|
      @user = result.model
    end
  end

  def create
    run User::Create do |result|
      session[:current_user_id] = result["model"].id
      return redirect_to user_posts_path(result["model"])
    end

    redirect_to login_signup_path, flash: { error:  "Passwords don't match" }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zombitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1> Twitter for Zombies</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zombitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1> Twitter for Zombies</h1>
      <%= link_to 'Your Posts', user_posts_path(@user) %> |
      <%= link_to 'All Posts', user_all_posts_path %> |
      <%= link_to 'Logout', login_signout_path, :method => :delete %>
    <%= yield %>
  </body>
</html>

app/views/login/_form.html.erb
<%= form_with scope: :user, url: post_path, local: true do |form| %>


  <% if flash[:error] %>
    <div id="error_explanation">
      <h2 style="color: red;">
        <%= flash[:error] %>
      </h2>
    </div>
  <% end %>

  <p>
    <%= form.label :login %><br>
    <%= form.text_field :login %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </p>


  <% if signup %>
    <p>
      <%= form.label :confirm_password %><br>
      <%= form.password_field :confirm_password %>
    </p>

    <p>
      <%= form.submit "Sign up" %>

      <%= link_to 'Sign in', login_index_path %>
    </p>

  <% else %>
    <p>
      <%= form.submit "Sign in" %>

      <%= link_to 'Sign up', login_signup_path %>
    </p>

  <% end %>

<% end %>

app/views/login/index.html.erb
<%= render partial: 'form', locals: {post_path: login_signin_path, signup: false} %>

app/views/login/signup.html.erb
<%= render partial: 'form', locals: {post_path: users_path, signup: true} %>

app/views/posts/_post.html.erb
<br>
  <button>
    <%= link_to 'X', [post.user, post],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </button>
  <strong>Post:</strong>
  <textarea rows="5" readonly>
    <%= post.body %>
  </textarea>

app/views/posts/_user.html.erb
<%= div_for(show_all) do |f| %>
<br>
  <strong>User:</strong>
  <%= f.user.login %>

<br>
  <strong>Post:</strong>
  <textarea rows="5" readonly>
    <%= f.body %>
  </textarea>

<% end %>

app/views/posts/all.html.erb
<h2> All Posts: </h2>
<%= render "user", show_all: @posts do |f| %>
<% end %>

app/views/posts/index.html.erb
<%= form_with scope: :new_post, url: user_posts_path, local: true do |form| %>


  <% if @error %>
    <div id="error_explanation">
      <h2 style="color: red;">
        Wrong credentials, try again
      </h2>
    </div>
  <% end %>

  <%= form.hidden_field :user, :value =>  @user %>
  <%= form.hidden_field :user_id, :value =>  @user.id %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.submit "Post" %>
  </p>

<% end %>

<%= render @user.posts %>